### ISSUE TITLE
Print function modifies the original character array.

### ISSUE THREAD

**Issue by AlexErAmp** [amperka/TroykaOLED#3]
Member function `void print(char* s, int x = OLED_THIS, int y = OLED_THIS);` can modify the original character array passed as an argument (`char* s`). I think the user does not expect such a side effect from this function. Therefore, we must remove it from the interface.

**Comment by nkrkv** [comment]
The signature should be idiomatic:

```cpp
void print(const char* s, int x, int y);
```

Note `const char*` instead of `char*`
